### PR TITLE
Support new command: terminate

### PR DESCRIPTION
**Pull request by hustclf**
- support new command: terminate

- add unit test case

### CODE REVIEW

**Comment by hustclf** [comment]
All tests passed in local environment, is any advice about the failure of travis-ci ?

```
➜  flink-deployer git:(feature-terminate) ✗ sh test-with-coverage.sh 
ok      flink-deployer/cmd/cli  1.026s  coverage: 61.2% of statements
ok      flink-deployer/cmd/cli/flink    1.058s  coverage: 83.6% of statements
ok      flink-deployer/cmd/cli/operations       2.266s  coverage: 82.8% of statements

```

**Comment by mrooding** [comment]
Isn't this a duplicate of the Cancel feature? Cancel also does a PATCH to `jobs/%v` although admittedly, your implementation does also support specifying the mode. Do you mind merging your terminate method with the already available Cancel method? I'm not sure about the travis build, I'll dig into this later on

**Comment by hustclf** [comment]
In fact, there is a little difference between Cancel and Terminate,  Terminate did not use `retryablehttp` to build the request, because `retryablehttp` will retry automatically when response status code is 500 and can not get the response body which includes error info about the [failure().](https://github.com/hashicorp/go-retryablehttp).

But when flink job is not stoppable and terminated with mode `stop`,  the status code is 500 with a json error info  body.
```
{
"errors": ["the flink job is not stoppable"]
}
``` 

Thus I am not sure whether the implement of Terminate can replace Cancel now,  I am planning to give another pr later to combine Cancel with Terminate when the difference is handle appropriately. Is that OK?

**Comment by mrooding** [comment]
I see, so the difference is mostly on our side since the Flink API will already do retrying for us. However, that only counts if our request actually made it to the flink cluster. If a networking error occurs during request time, we would still need retryablehttp to retry it for us. I think we can use [CheckRetry](https://godoc.org/github.com/hashicorp/go-retryablehttp#CheckRetry) with retryablehttp to exclude that specific 500 error from retrying. This would solve all cases right? 

Besides that, I noticed that you're not using `c.newRequest(..)` to do the call, which indeed skips using retryablehttp but also skips adding the authentication headers that were added in version 1.1.

All by all, it'd be great to have only 1 CLI command that handled this logic in a proper way instead of merging this Terminate functionality which is similar to Cancel but skips authentication added in 1.1

Let me know what you think

**Comment by hustclf** [comment]
Yes, you are right, I will try `CheckRetry` and left only 1 CLI command, but I prefer to rename `Cancel` to 'Terminate',  to keep the same with [flink rest api](https://ci.apache.org/projects/flink/flink-docs-stable/monitoring/rest_api.html#jobs-jobid-1),  do you agree ?

**Comment by mrooding** [comment]
Agreed. Changing it to terminate to support both cancel and stop makes the most sense. Looking forward to reviewing it again.

**Comment by hustclf** [comment]
Should I open a new pr for clean commit history,  or just use the current pr, which is better? @mrooding

**Comment by mrooding** [comment]
whatever you choose. I'm fine with both. If you do keep this one, please update the title of the PR.

**Comment by hustclf** [comment]
Close current pr for clean commit history,  new pr is #37

**Pull request closed without merging**
